# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /mnt/c/Users/Sacha/Documents/RedEye/clion-2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /mnt/c/Users/Sacha/Documents/RedEye/clion-2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/Sacha/Documents/Coding Documents/C++/MazeCreator"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/Sacha/Documents/Coding Documents/C++/MazeCreator"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/mnt/c/Users/Sacha/Documents/RedEye/clion-2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/mnt/c/Users/Sacha/Documents/RedEye/clion-2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Sacha/Documents/Coding Documents/C++/MazeCreator/CMakeFiles" "/mnt/c/Users/Sacha/Documents/Coding Documents/C++/MazeCreator/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Sacha/Documents/Coding Documents/C++/MazeCreator/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MazeCreator

# Build rule for target.
MazeCreator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MazeCreator
.PHONY : MazeCreator

# fast build rule for target.
MazeCreator/fast:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/build
.PHONY : MazeCreator/fast

Maze.o: Maze.cpp.o

.PHONY : Maze.o

# target to build an object file
Maze.cpp.o:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/Maze.cpp.o
.PHONY : Maze.cpp.o

Maze.i: Maze.cpp.i

.PHONY : Maze.i

# target to preprocess a source file
Maze.cpp.i:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/Maze.cpp.i
.PHONY : Maze.cpp.i

Maze.s: Maze.cpp.s

.PHONY : Maze.s

# target to generate assembly for a file
Maze.cpp.s:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/Maze.cpp.s
.PHONY : Maze.cpp.s

MazeSolver.o: MazeSolver.cpp.o

.PHONY : MazeSolver.o

# target to build an object file
MazeSolver.cpp.o:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/MazeSolver.cpp.o
.PHONY : MazeSolver.cpp.o

MazeSolver.i: MazeSolver.cpp.i

.PHONY : MazeSolver.i

# target to preprocess a source file
MazeSolver.cpp.i:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/MazeSolver.cpp.i
.PHONY : MazeSolver.cpp.i

MazeSolver.s: MazeSolver.cpp.s

.PHONY : MazeSolver.s

# target to generate assembly for a file
MazeSolver.cpp.s:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/MazeSolver.cpp.s
.PHONY : MazeSolver.cpp.s

Tile.o: Tile.cpp.o

.PHONY : Tile.o

# target to build an object file
Tile.cpp.o:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/Tile.cpp.o
.PHONY : Tile.cpp.o

Tile.i: Tile.cpp.i

.PHONY : Tile.i

# target to preprocess a source file
Tile.cpp.i:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/Tile.cpp.i
.PHONY : Tile.cpp.i

Tile.s: Tile.cpp.s

.PHONY : Tile.s

# target to generate assembly for a file
Tile.cpp.s:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/Tile.cpp.s
.PHONY : Tile.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/MazeCreator.dir/build.make CMakeFiles/MazeCreator.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MazeCreator"
	@echo "... Maze.o"
	@echo "... Maze.i"
	@echo "... Maze.s"
	@echo "... MazeSolver.o"
	@echo "... MazeSolver.i"
	@echo "... MazeSolver.s"
	@echo "... Tile.o"
	@echo "... Tile.i"
	@echo "... Tile.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

